#!/bin/bash
ip_reg='(?:[0-9]{1,3}\.){3}[0-9]{1,3}'
ddns_check() {
    res=$(curl -L -s http://ipecho.net/plain)
    token=$(jq -r '.token' ddns.json)
    records=$(jq '[.records[]]' ddns.json)
    echo $res
    echo $token
    echo ${records[0]}
}

set_api_token() {
    echo "Setting API Token to $3"
}

arg_len=$#
echo $arg_len
if arg_len==0; then 
    ddns_check
else 
    echo hello
fi

case "$1" in
    --set-token) set_api_token;;
    *) echo "error";;
esac
echo finished task